### ISSUE TITLE
اضافه کردن کتابخانه

### ISSUE THREAD

**Issue by fatemeh2sh** [persiandate/PersianAndroidDateTimePicker#1]
چطوری کتابخانه رو به پروژه ام اضافه کنم؟. گردل نداره؟
Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
اینا مشکل دارن

**Comment by Tabrizian** [comment]
I’ll provide a Gradle installation method very soon. Thanks for starting to use it. :)

**Comment by fatemeh2sh** [comment]
thanks for useful library, i add library to my project.
i solve my problem, i remove this "apply from: 'gradle-mvn-push.gradle' ";
library add successful. :-)
@Tabrizian

**Comment by Tabrizian** [comment]
Perfect 👌🏻 let us know if there is any further problem.
